services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    user: root
    restart: always
    #    network_mode: host
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672
    volumes:
      - ./lib:/var/lib/rabbitmq
      - ./etc:/etc/rabbitmq
      - ./logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=rabbitmq-1
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=158818
    command:
      - cd /bin/bash && rabbitmq-plugins enable rabbitmq_management


