services:
  nginx:
    image: nginx
    container_name: nginx
    user: root
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    build:
      context: .
      dockerfile: ./Dockerfile
