services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - 8066:8080
      - 50000:50000
    volumes:
      # Jenkins 数据持久化
      - /opt/jenkins_data:/var/jenkins_home
      # Docker 支持（容器中控制宿主机容器）
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker:/usr/libexec/docker
      - /usr/lib/docker:/usr/lib/docker
      # SSH 密钥
      - /root/.ssh:/root/.ssh

