services:
  github-runner:
    image: ghcr.io/actions/actions-runner:latest
    container_name: github-runner
    restart: unless-stopped
    environment:
      RUNNER_NAME: my-server-runner
      RUNNER_WORKDIR: /tmp/runner
      RUNNER_TOKEN: ${RUNNER_TOKEN}
    volumes:
      - runner-workdir:/tmp/runner
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/bash", "-c"]
    command: >
      ./config.sh \
      --url https://github.com/nechao136 \
      --token ${RUNNER_TOKEN} \
      --name ${RUNNER_NAME} \
      --work ${RUNNER_WORKDIR} \
      --unattended \
      --replace \
      && ./run.sh
