services:
  github-runner:
    image: ghcr.io/actions/actions-runner:latest
    container_name: github-runner
    restart: unless-stopped
    environment:
      RUNNER_NAME: my-server-runner
      RUNNER_WORKDIR: /tmp/runner
      RUNNER_TOKEN: ${RUNNER_TOKEN}
    volumes:
      - runner-workdir:/tmp/runner
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: bash -c "./config.sh --url https://github.com/nechao136 --token AHV7KLW6MFFK5FHYS6H3AXTI3CTP4 --unattended && ./run.sh"

volumes:
  runner-workdir:
