services:
  minio:
    image: minio/minio:latest
    container_name: minio
    user: root
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=158818
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
